[package]
name = "chat_server"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
hyper = { version = "1.3", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }


# Web framework
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }

# Utilities
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
argon2 = "0.5"
jsonwebtoken = "9"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls", "uuid"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
rand = "0.8"
anyhow = "1"
headers = "0.4"
